Fix taylor expand
Matt-Ord/reduced_state_caldeira_leggett pull request #10
Opened 2024-08-01 12:18 UTC by Winnie08L

2024-08-02 11:45 UTC, Matt-Ord requested changes
Some small changes requested - I would suggest moving the compare error stuff to another follow-up pr to get the rest of it merged sooner.

2024-08-02 11:45 UTC, Matt-Ord commented on examples/main.py
> +    plot_gaussian_noise_kernel(system, config, fit_method="poly fit", n=5)
I would add a new kernel.py file to the examples folder to put these in instead

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    """Compare the errors between kernels obtained using different methods: general taylor expansion
Fix doc comment

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    #     true_noise["basis"],
remove dead code

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    gaussian noise is used here for testing.
fix doc comment

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +fit_method = Literal["explicit", "poly fit", "fft"]
add to SimulationConfig

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        case "poly fit":
move this logic into get_noise_operators, and add the 'eigenvalue' method (i.e. current technique) to FitMethod

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def plot_gaussian_noise_kernel(
rename to plot_noise_kernel

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    basis_x = stacked_basis_as_fundamental_position_basis(hamiltonian["basis"][0])
just use get_noise_kernel in system.py

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        case "explicit":
It might be nice (in a follow up pr) to add a poly fit which fits the whole kernel and then truncates the series - it might be better than local polyfit (i.e. closer to explicit)

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    ax.set_title("noise kernel, fit method = %s, n = %d" % (fit_method, n))
use f strings (ie f"fit method = {method}")

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    fig, _, line3 = plot_data_1d_x(
use plot_isotropic_noise_kernel_1d_x

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def plot_isotropic_kernel(kernel: IsotropicNoiseKernel[_B0], *, n: int = 1) -> None:
use one in lib/surface_potential_analysis (plot_isotropic_noise_kernel_1d_x)

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_noise_operators_taylor_expansion(
this belongs in surface_potential_analysis (probably in kernel/fit.py next to get_coefficient_matrix_taylor

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    The noise operators formed using the2n+1 lowest fourier terms, and the corresponding coefficients.
the 2n+1

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    # get coeff
remove commet

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    ax.set_title("noise kernel percentage error comparison")
"comparison of noise kernel percentage error"

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    line.set_label("poly fit kernel error")
set label immediately after plot_data_1d_x

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def get_noise_kernel_percentage_error(
should return a value list - also what if they have a different basis - you will need to do a basis conversion in this case

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    fig, ax, line = plot_data_1d_x(
add a new plot_isotropic kernel error to kernel/plot.py and use that instead.  It should take two Isotropic kernels.

2024-08-02 11:45 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    n: int = 1,
add n to SystemConfig

2024-08-02 11:46 UTC, Matt-Ord requested changes

2024-08-02 11:46 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
>          )
list_basis=fundamental_transformed_stacked_basis_from_shape(config.shape)

2024-08-02 11:47 UTC, Matt-Ord commented
Also remember to merge/rebase onto main!

2024-08-02 13:25 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +        case "poly fit":
I am also moving the get_noise_operators_taylor_expansion to kernel.py, same file as get_noise_op to avoid circular import

2024-08-02 13:58 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +        case "poly fit":
i might need to add more arguments to the function get_noise_op to generate the parameters needed for gaussian, and can i rename this function to something like "get_noise_operators_full_eigenvalue"? otherwise it has the same name as the function defined in system.py and i can't use this function in reduced_caldeira/plot.py

2024-08-02 14:11 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +    # get coeff
i renamed new_noise_operators to get_noise_operators_fft

2024-08-02 15:12 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +def plot_gaussian_noise_kernel(
but this one plots the gaussian noise kernel, showing both the true one and the fitted one, not a general plot_noise_kernel, a plot_isotropic_kernel which plots a general isotropic kernel is defined in a separate function

2024-08-02 15:23 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +def plot_gaussian_noise_kernel(
but this one plots a gaussian noise kernel? since get_noise_kernel from system.py returns a gaussian

2024-08-02 15:44 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def plot_gaussian_noise_kernel(
If you feel strongly keep it how it is- but since get_kernel could return anything (IE maybe we want to add another option to the config to support lorentzian). Also the word gaussian is not useful as there is no plot lorentzian equivalent

2024-08-02 16:13 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +    fig, ax, line = plot_data_1d_x(
can it take one isotropic kernel and a operator list instead? the operator list will be generated from different fitting methods

2024-08-02 16:31 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    fig, ax, line = plot_data_1d_x(
I think it would be clearer to call as_isotropic_kernel() outside the function and then have a plot comparing two isotropic kernels, since this feels like a more general thing one may want to do whereas kernel Vs operator seems application specific

2024-08-02 17:06 UTC, Winnie08L commented
to be tested after fixing circular import problem in surface_potential_analysis

2024-08-06 20:43 UTC, Matt-Ord commented
Remember to merge/ rebase on top of main

2024-08-08 14:08 UTC, Matt-Ord requested changes
Just some small changes - I would suggest adding get_potential() which gets the relevent (1d or 2d) potential and use this in get_full_hamiltonian and get noise operators

2024-08-08 14:08 UTC, Matt-Ord commented on examples/kernel.py
> +system = HYDROGEN_NICKEL_SYSTEM
if __name__ == __main__

2024-08-08 14:08 UTC, Matt-Ord commented on examples/kernel.py
> +plot_basis_states(system, config)
this is not relevant to this example

2024-08-08 14:08 UTC, Matt-Ord commented on examples/main.py
> +    config1 = SimulationConfig(
go back to the previous example, maybe include both 1d and 2d though

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def plot_new_noise_operators(
replace this with a plot_noise_operators function - should use get_noise_operators

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    kernel_isotropic_ = as_isotropic_kernel_from_diagonal(
only use _ after the name as a last resort 9ie for lambda_

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    basis_x = stacked_basis_as_fundamental_position_basis(basis)
should compare against get_noise_operators for a config with no truncation , not by doing it manually

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        get_diagonal_kernel_from_operators(
add a get_isotropic_kernel from operators in a new baranch of surface_potential_analysis.

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    fit_op = get_temperature_corrected_noise_operators(system, config)
temperature_corrected =

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    ax.set_title(
```
ax.set_title(
        f"noise kernel, fit method = {config.FitMethod}, n = {config.n_polynomial},"
        f"temperature = {config.temperature}",
    )
```

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    line3.set_label("fitted noise, with temperature correction")
if temperature correction has no effect, why do we plot it here?

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    # return get_noise_kernel_generic(operators)
remove comment

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    return get_gaussian_isotropic_noise_kernel(basis, a, lambda_)
should be derived from get noise operators

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    basis = hamiltonian["basis"][0]
use get_noise_kernel here

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +                basis,
some type issues here

2024-08-08 14:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    hamiltonian = get_hamiltonian(system, config)
using get_potential()["basis"] will be cheaper here

2024-08-08 14:56 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +    line3.set_label("fitted noise, with temperature correction")
removed, was plotted to test get_temp_corrected_op function

2024-08-08 14:58 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +    return get_gaussian_isotropic_noise_kernel(basis, a, lambda_)
but wouldn't this give the fitted kernel instead? i thought this function is to return the true kernel, instead of the fitted one?

2024-08-08 15:01 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +                basis,
this case is actually removed, might still be in the file in the old version, cuz i think this function only fit gaussian kernel, while others in theory can fit a general isotropic one

2024-08-08 15:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    return get_gaussian_isotropic_noise_kernel(basis, a, lambda_)
Yeah the intention is to return the fitted kernel

2024-08-08 15:08 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +                basis,
Yeah that sounds sensible - I added this myself but feel free to remove it

2024-08-08 15:33 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +    basis_x = stacked_basis_as_fundamental_position_basis(basis)
added new function plot_true_noise_kernel which get op from get_noise_op_..._stacked_fft and no truncation

2024-08-11 17:46 UTC, Matt-Ord approved these changes

2024-08-11 17:46 UTC, merged