Compare error
Matt-Ord/reduced_state_caldeira_leggett pull request #11
Opened 2024-08-07 16:44 UTC by Winnie08L

2024-08-11 17:51 UTC, Matt-Ord requested changes

2024-08-11 17:51 UTC, Matt-Ord commented on examples/example.py
> +plot_noise_kernel(system, config)
needs a rebase - I would also the error plot to kernel.py

2024-08-11 17:51 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    to_compare: bool = False,
just make config1 optional here? and remove to_compare. Rename config1 to base_config, and default to fft with no trucation

2024-08-12 11:00 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +    to_compare: bool = False,
i will fix these review comments in modify_compare_error_func in the time_and_compare_error branch

2024-08-15 08:50 UTC, Matt-Ord commented
Converted to draft for visibility, just click ready to review when it's ready for me

2024-08-15 12:06 UTC, closed without merging