Time and comapre error
Matt-Ord/reduced_state_caldeira_leggett pull request #13
Opened 2024-08-09 14:31 UTC by Winnie08L

2024-08-13 16:32 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
need tidy up plot functions for different fit method to make it more general

2024-08-15 08:50 UTC, Matt-Ord commented
Converted to draft for visibility, just click ready to review when it's ready for me

2024-08-15 13:15 UTC, Matt-Ord commented
@Winnie08L you will need to resolve these conflicts before it can be merged

2024-08-15 13:56 UTC, Matt-Ord requested changes

2024-08-15 13:56 UTC, Matt-Ord commented on examples/kernel.py
> +    # plot_operators_fit_time_against_n_polynomial(system, config, n_terms_range, n_run)
need to clean up this example file

2024-08-15 13:56 UTC, Matt-Ord commented on examples/main.py
> +    plot_noise_kernel(system, config)
I think the old example should be kept, just do kernel stuff in examples/kernel

2024-08-15 13:56 UTC, Matt-Ord commented on myscript.prof
binaries should not be bushed to github

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    potential = get_potential_2d(system, config.shape, config.resolution)
get_potential

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    fig1, ax1, _ = plot_operator_along_diagonal(as_operator(op), measure="real")
plot against x - see my pr

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        f"noise kernel, fit method = {config.fit_method}, n = {config.n_polynomial}, temperature = {config.temperature}",
this needs to be merged with main

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +# fitted with complexity
remove chatgpt comment

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    def _complexity(x, a):
type annotations, rename to something like _get_complexity. Function names should always be descriptive of what it is they do

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +                label=f"complexity\n {popt[0]}" r"$N \cdot$" "ln" r"$N$",
Implicitly concatenated string literals on one line

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +                popt[0] * np.ones(len(xdata)),
use cast() on scipy.optimize.curve_fit to solve these type errors

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +
this fitting stuff should be moved to a new function

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +                popt[0] * xdata * np.log(xdata),
have a get_fit_function method, or use _complexity directly to make this the same for each method

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    runtime = []
```
= list[float]()
```
or 
```
: List[float] = []
```
to avoid type issues

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    xdata = np.array(n_data_pts)
prefer x_data to xdata

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +            times_fit.append(
why do you need this if statement?

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_operators_fit_time(
why not just time get_operators - and why a list[time] not float. If the overhead of getting the cos and sin operators is larger than the cost of calculating eigenvalues then one would argue that the benchmark is not representative of real-world performance

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    base_config: SimulationConfig | None = None,
should show error between base_kernel and fitted_kernel?

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        assert_isotropic=False,
assert_isotropic should be true

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    base_kernel = get_diagonal_kernel_from_diagonal_operators(base_operators)
just use get_noise_kernel

2024-08-15 13:56 UTC, Matt-Ord commented on examples/kernel.py
> +        shape=(2,),
should be the same shape and resolution (do config.shape...)
define this next to where it is used

2024-08-15 13:56 UTC, Matt-Ord commented on examples/kernel.py
> +        base_config=config1,
maybe accept a list of configs instead?

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    n_run: int,
values that are just an int should be keyword only

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    size: np.ndarray[tuple[int, int], np.dtype[Any]],
what is the significance of tuple[int, int]. Does it need to be np.int_

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    np.random.shuffle(size)
Replace legacy `np.random.shuffle` call with `np.random.Generator`

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        for n in range(n_run):
I think it would be better if you waiched the order of this for loop and shuffled size on each go through

2024-08-15 13:56 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    for s in size:
rng.permutation(size)

2024-08-15 15:07 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +            times_fit.append(
cuz i want it to have a break every 100 runs

2024-08-15 15:15 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +def get_operators_fit_time(
cuz get_time_stacked_taylor and get_time_explicit returns [runtime of the fit method itself (ie only the fitting step), runtime of getting cos and sin operators], but yes i'll change them to time the whole get_op function instead, although this would include the time taken to get_potential and basis and gaussian parameters etc

2024-08-15 15:28 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +    base_config: SimulationConfig | None = None,
so you mean the base_kernel is the true_kernel? cuz what i meant here is to have an optional fitted_kernel1 built from config1(now renamed to "base_kernel"), which use a different fit method or n_polynomial from config, and so the error of different methods can be directly compared

2024-08-15 15:33 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    base_config: SimulationConfig | None = None,
Hmm actually yeah you are right this is probably better - but in this case I would just accept a list of configs instead of config,other config

2024-08-17 16:12 UTC, Matt-Ord requested changes
Almost there - You also need to update surface potential analysis - I don't think the timing stuff has been removed yet?

2024-08-17 16:12 UTC, Matt-Ord commented on examples/kernel.py
> +    plot_isotropic_kernel_percentage_error(
Define config1 down here, next to where it is used

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +) -> list[list[list[float]] | list[float]]:
If you are returning two things, it is best to use tuple, ie tuple[list[float], list[float]].
In this case, I would say this should probably return a StatisticalValueList[FundamentalBasis[int]], so it plays nice with the rest of surface potential analysis

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        shuffled_param_list = rng.permutation(parameter)
```
for i in rng.permutation(np.arange(parameter.size)):
```

that way you don't need to use argwhere

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    runtime: list[list[float]] = [[] for _ in range(len(parameter))]
use np.zeroes() here. You know the shape so might as well do the full allocation upfront.

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        if (n + 1) % 100 == 0 and n != 0:
Have you tested this - does it actually make the benchmark more reliable now you have swapped the order of iteration...

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    runtime = get_time_and_run(system, config, size, n_run=n_run)[0]
this is very wasteful - use 
```
runtime, error = get_time_and_run
```

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    n_data_pts = size * config.resolution[0]
not needed until later, as a general rule try to define variables as close as possible to where you need them. It makes it easier to read (less to keep in your head at once)

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    size: np.ndarray[tuple[int], np.dtype[Any]],
np.dtype[np.float64]

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    n_run: int,
add a sensible default

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    size: np.ndarray[tuple[int], np.dtype[Any]],
sizes, since it is a list of size. What about 2d here? maybe should be a tuple[ndarray]? It would also be good to add a doc comment and specify that size is the size param in the config object

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    config: SimulationConfig,
maybe it should just take n_states and fit_method - are the other params in config completely irrelevent?

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        case "fitted polynomial" | "explicit polynomial":
use ax.plot() rather than plt.plot(). If it is a line of best fit use a line rather than "o" markers. You can add a get_complexity_label to avoid this match statement here.

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    plt.errorbar(
ax.errorbar

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    runtime = get_time_and_run(system, config, n_range, n_run=n_run)[0]
again wasteful

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    n_terms_range: int,
max_n_polynomial is a better name, but I think the api should mirror that of 'against_n_states' (ie pass a list of n_polynomial

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    n_run: int,
add default

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +                _get_complexity(n_range, popt[0]),
similar comment with labels, match statement, line instead of o etc from the other function. This looks like it could be extracted out into a shared function which takes a function (get complexity) etc.

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    plt.xlabel("n terms")
again ax.errorbar, ax.set_xlabel is prefered as it is less implicit

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    config_list: list[SimulationConfig],
just configs: list[SimulationConfig], and maybe Sequence[SimulationConfig] so a user can also use a tuple

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    line: list[Line2D] = [hold_place for _ in range(len(config_list))]
lines = ... And I would just leave it empy at first and do lines.append(). What if len(config_list) is zero? use fig, ax = get_figure(None) to get an axis for the for loop, and you should get true kernel for each config (what if they had a different true kernel?)

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    for i in range(len(config_list)):
for config in config_list, or use enumerate() if you need i. If you use .append() though I dont think you need i

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        "comparison of noise kernel percentage error,\n"
Capital c here

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    _, ax, hold_place = plot_isotropic_kernel_error(true_kernel, true_kernel)
this seems kinda a hack

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +        np.ndarray[tuple[int], np.dtype[np.float64]],
tuple [np.ndarray[tuple[int], np.dtype[np.float64]], Any]

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    def _get_complexity(x, a):
add type annoations

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_operators_fit_time(
i'm not sure why this is needed if it is the same as get operators but is otherwise timed - can't you just move the timing to where it is used in plot.py?

2024-08-17 16:12 UTC, Matt-Ord commented on myscript.prof
No binaries - I would add *.prof to the .gitignore to stop them accidentally getting onto github

2024-08-17 16:12 UTC, Matt-Ord commented on examples/kernel.py
> +    plot_isotropic_kernel_percentage_error(
plot_kernel_error_comparison(...)

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def get_time_and_run(
get_runtime_of_get_operator() or some more descriptive name. and should be private (ie begin with an underscore)

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    error = get_time_and_run(system, config, n_range, n_run=n_run)[1]
doesn't this compare against n_states not n_polynomial? Maybe it would be good to make this take a list of configs so it is more general?

2024-08-17 16:12 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    parameter: np.ndarray[tuple[int], np.dtype[Any]],
parameter is a confusing name (but I think maybe should just take a list of configs?)

2024-08-20 10:31 UTC, merged