2d isotropic kernel
Matt-Ord/reduced_state_caldeira_leggett pull request #15
Opened 2024-08-22 14:16 UTC by Winnie08L

2024-08-27 13:59 UTC, Matt-Ord requested changes
Great job getting this working - some very tricky theory to get working in code. I have left a few comments - basically if possible it would be good if we could undo this separation between 1d and 2d

2024-08-27 13:59 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_2d_noise_op_full(
this should be abstracted over in get_noise_operators_real_isotropic_taylor_expansion_stacked

2024-08-27 13:59 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_2d_noise_op_separate(
this function has type errors. Is it possible to use the same function to get the operators in both the 1d and 2d case?

2024-08-27 13:59 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_2d_noise_kernel(
this looks generic over n dimensions to me - is there a reason this is separate from the 1d case

2024-08-27 13:59 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +        "data": _outer_product(*full_data).ravel(),
_outer_product stuff should all be sin surface_potential_analysis

2024-08-27 13:59 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def try_plot_2d_kernel(
what is the significance of try_plot vs just plot here?

Also, do we actually need a separate 1d and 2d function here?

2024-08-27 13:59 UTC, Matt-Ord commented on lib/surface_potential_analysis
does this rely on your surface potential analysis branch - if so is that pr ready to review?

2024-08-27 14:52 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +def get_2d_noise_op_full(
if fft is also using this method (separating kernel into independent directions), then may need to keep this a independent function instead of inside taylor_stacked?

2024-08-27 15:11 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_2d_noise_op_full(
Yes, it can be an independent function called within Taylor stacked

2024-08-27 16:21 UTC, Winnie08L commented
i also made explicit polynomial work as well, but i think the 'plot full noise kernel' part at the end of the plot_noise_kernel function only work for 1d?

2024-08-28 13:23 UTC, Matt-Ord requested changes

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +        IsotropicNoiseKernel[FundamentalPositionBasis[Any, Any]], ...
fomat

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    full_isotropic_kernel = get_full_kernel_from_independent(kernels)
spa should do this itself

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    # now poly fit and explicit fit working for general dimension
remove comment

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +        operators_list = tuple(
should all work on the full kernel, but internally split the kernel in ais kernels inside get_noise_operators_real_isotropic_taylor_expansion

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +) -> tuple[
this should return the noise operators

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +                range(2 * config.n_polynomial[0] + 1),
the types are wrong here

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> -    return get_isotropic_kernel_from_diagonal_operators(operators)
revert this change

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +) -> tuple[IsotropicNoiseKernel[FundamentalPositionBasis[Any, Any]], ...]:
remove this

2024-08-28 13:23 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_full_noise_operators(
remove this from there - this is an implementation detail of the polynomial fitting

2024-08-28 14:08 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +    full_isotropic_kernel = get_full_kernel_from_independent(kernels)
so you mean this should be moved to spa??...or ...?

2024-08-28 14:10 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +) -> tuple[
the full noise op (not the two sets along independent axes)? but they will be needed to construct the fitted kernels later..?

2024-08-28 15:04 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +                range(2 * config.n_polynomial[0] + 1),
fft to be fixed in later commits

2024-08-30 12:21 UTC, Winnie08L commented
assert_isotropic still failed, max relative tolerance 1.63... which is quite big...

2024-08-30 13:33 UTC, Winnie08L commented
i see why, i just made plotting work, and i plotted out the operators for poly fit, the ones along x0 axis is always a const, they are not correct

2024-09-01 12:45 UTC, Matt-Ord approved these changes

2024-09-01 12:45 UTC, merged