New noise op
Matt-Ord/reduced_state_caldeira_leggett pull request #9
Opened 2024-07-23 10:36 UTC by Winnie08L

2024-07-29 18:10 UTC, Matt-Ord requested changes
Some great work here - this takes us one step closer to working in 2d - very exciting!

2024-07-29 18:10 UTC, Matt-Ord commented on examples/main.py
> +
Fix formatting

2024-07-29 18:10 UTC, Matt-Ord commented on examples/main.py
> +
Fix formatting

2024-07-29 18:10 UTC, Matt-Ord commented on examples/main.py
> +    # plot_basis_states(system, config)
Remove commented code

2024-07-29 18:10 UTC, Matt-Ord commented on examples/main.py
> +
Might be nice to add a new example which has a comparison of different noise operators IE examples/noise.py

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/dynamics.py
> +    # operators = new_noise_operators(system, config)
Remove commented code

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +
Fix formatting

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    potential = get_2d_111_potential(system, config.shape, config.resolution)
Is this correct

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +#     fig.show()
Remove commented code

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +# 2d
Is there a reason this was added back in?

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    # try--------------------------------------------------------------------
Remove this comment

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    # define a variable n: the number of trig terms to include, in total 2n+1 terms
Remove this comment - or move it next to the code it refers to

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    if n == 0:
Remove the special case - see my pr/ merge it into this if you want inspiration

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    if n == 0:
Similarly remove special case

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    and also their cprresponding coefficients.
Typo

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    """To fit the noise correlation using trig functions generated from hamiltonian,
Doc comments should focus on what it returns not how 

IE

Calculates the noise operators for a Gaussian noise kernel, using an explicit Taylor expansion 

This function makes use of the analytical expression for the Taylor expansion of gaussian noise 
Ae^(-x^2/2 lambda) = ...
to find the 2n+1 lowest Fourier coefficients 

Inline comments should provide algorithmic details IE how does it work

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    system: PeriodicSystem,
Should just take a, lambda and basis as arguments , and move into gaussian.py

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def solve_linear_gaussian_isotropic_noise(
Rename to get_gaussian_operators_explicit_taylor

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +# try gaussian--------------not done-------------------------------------------
ReMove from pr if not done

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def solve_linear_lorentzian_isotropic_noise(
Did you get this working - if not remove or fix

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    hamiltonian = _get_full_hamiltonian(system, config.shape, config.resolution)
Add an assertion that ndim is 1 if this only supports 1d for now. Is it possible to do this in N dimensions (using n different lambda values...)

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    if n == 0:
Remove if statement by making else branch work for n=0

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def get_lorentzian_isotropic_noise_kernel(
Probably should live in surface potential analysis.

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +) -> SingleBasisDiagonalNoiseOperatorList[
Needs doc comments

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    if n == 0:
Again remove branches and explain algorithm in comments

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +        coeff = np.linalg.solve(coeff_to_solve, true_noise_coeff)
This solve step should be extracted into it's own function and used everywhere you solve coefficients

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    by taylor expanding around origin.
Typo

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +def solve_linear_general_isotropic_noise(
get_noise_operators_taylor_expansion()

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    by taylor expanding around origin.
Use numpy style docs to give information about the Arguments

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    weight = pad_ft_points(np.ones(2 * n + 1), (basis_x.n,), (0,))
Comment here - why is not immediately obvious

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    fit_degree = np.arange(0, 2 * n + 1, 2)
Just declare inline

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +        fit_degree,
Declare inline - and use keyword arguments to maintain clarity

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    nk_points = (
Displacements=.... And maybe use definition inside gaussian.py

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    delta_k = 2 * np.pi / delta_x
This is dk

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    true_noise_coeff = np.polynomial.Polynomial.fit(
noise_coefficients = ...

And this is noise_polynomial

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    coeff_to_solve = np.array(
operator_coefficients

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    coeff = np.linalg.solve(coeff_to_solve, true_noise_coeff)
Extract to function

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    # fitted noise kernel-----------------------------
Remove comment

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    hamiltonian = _get_full_hamiltonian(system, config.shape, config.resolution)
Use of private method

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    fig, _, line1 = plot_data_1d(
plot 1d_x, and add a plot isotropic kernel function

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    # 1d lorentzian---------------------------
Remove comment

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def plot_isotropic_noise_kernel(
plot_gaussian_noise_kernel

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +def plot_new_noise_operators(
Remove?

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/plot.py
> +    basis: TupleBasisLike[*tuple[Any, ...]],
Where is this code used?

2024-07-29 18:10 UTC, Matt-Ord commented on reduced_state_caldeira_leggett/system.py
> +    sines = [
extract to function if used twice

2024-07-30 10:25 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +    basis: TupleBasisLike[*tuple[Any, ...]],
this is for the plot 2d 222 state against t, but the function has some bugs that are not yet fixed, i'll remove this part first and submit as a seperate pr once fixed

2024-07-30 10:26 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +def plot_new_noise_operators(
this is to plot out explicitly the new noise operator used for fitting -do we not need this? then i'll also remove this

2024-07-30 10:40 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +    fig, _, line1 = plot_data_1d(
i added a plot_isotropic_kernel function which takes a general isotropic kernel, so i think i'll remove the plot_lorentzian, since it's another special case and there already exists one in the plot_gaussian_noise

2024-07-30 10:43 UTC, Winnie08L commented on reduced_state_caldeira_leggett/plot.py
> +    hamiltonian = _get_full_hamiltonian(system, config.shape, config.resolution)
but this is needed to plot the gaussian?

2024-07-30 10:56 UTC, Winnie08L commented on reduced_state_caldeira_leggett/system.py
> +# 2d
i forgot to delete this when resolving the conflicts

2024-08-11 17:47 UTC, Matt-Ord commented
@Winnie08L closing because I think all of these changes were in the other one?

2024-08-11 17:47 UTC, closed without merging